apiVersion: v1
kind: Service
metadata:
  name: apnaride-backend
  namespace: apnaride
spec:
  selector:
    app: apnaride-backend
  ports:
    - protocol: TCP
      port: 9031
      targetPort: 9031
  type: ClusterIP
