apiVersion: v1
kind: Service
metadata:
  name: apnaride-frontend
  namespace: apnaride
spec:
  selector:
    app: apnaride-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
