apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apnaride-ingress
  namespace: apnaride
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: apnaride.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: apnaride-frontend
                port:
                  number: 80
